'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class assignDepartment

    '''<summary>
    '''cboFaculty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboFaculty As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboSchoolA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSchoolA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lstDepartmentA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstDepartmentA As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''btnAddB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddto As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAddA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddfr As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cboSchoolB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSchoolB As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lstDepartmentB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstDepartmentB As Global.System.Web.UI.WebControls.ListBox
End Class
